/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enrichingexistingontology;

import com.eeo.jwnl.JwnlAPI;
import com.eeo.model.NewConcept;
import com.eeo.model.ParentConcept;
import java.util.ArrayList;

/**
 *
 * @author Jabed hasan
 */
public class DefineNewConcept extends javax.swing.JFrame {

    /**
     * Creates new form DefineNewConcept
     */
    public String conceptName;
    public String defineNewConcept;
    public String[] conceptHead;
    
    public String selectedHead;
    public DefineNewConcept(String conceptName, String defineNewConcept, String[] conceptHead) {
        initComponents();
        this.conceptName = conceptName;
        this.defineNewConcept = defineNewConcept;
        this.conceptHead = conceptHead;
        initUI();
    }
    
     public void initUI(){
         
         conceptNameTxtFld.setText(conceptName);
         defineNewConceptTxtArea.setText(defineNewConcept);
         for (String head : conceptHead) {
             if(!head.equals(""))
             conceptHeadComboBox.addItem(head);
         }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlelabel = new java.awt.Label();
        conceptNameLbl = new java.awt.Label();
        conceptNameTxtFld = new java.awt.TextField();
        defineNewConceptLbl = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        defineNewConceptTxtArea = new javax.swing.JTextArea();
        headNewConceptLbl = new java.awt.Label();
        cancelButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        conceptHeadComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enriching Existing Ontology");

        titlelabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        titlelabel.setText("Create New Concept");

        conceptNameLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        conceptNameLbl.setText("New Concept Name");

        conceptNameTxtFld.setText("textField1");

        defineNewConceptLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        defineNewConceptLbl.setText("Defien New Concept");

        defineNewConceptTxtArea.setColumns(20);
        defineNewConceptTxtArea.setRows(5);
        jScrollPane1.setViewportView(defineNewConceptTxtArea);

        headNewConceptLbl.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        headNewConceptLbl.setText("Define head of the new concept");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        conceptHeadComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                conceptHeadComboBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(458, 458, 458)
                        .addComponent(titlelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(defineNewConceptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conceptNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(headNewConceptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(conceptNameTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(conceptHeadComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addGap(314, 314, 314)
                .addComponent(nextButton)
                .addGap(325, 325, 325))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titlelabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(conceptNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(conceptNameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(defineNewConceptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(headNewConceptLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conceptHeadComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(206, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nextButton)
                            .addComponent(cancelButton))
                        .addGap(120, 120, 120))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void conceptHeadComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_conceptHeadComboBoxItemStateChanged
       selectedHead  = (String) evt.getItem();
    }//GEN-LAST:event_conceptHeadComboBoxItemStateChanged

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        System.out.println("Current wiki-Category Head : "+conceptNameTxtFld.getText());
        System.out.println("Alternative Definition : "+defineNewConceptTxtArea.getText());
        System.out.println("Parent Concept Head : "+selectedHead);
        
        ArrayList<ParentConcept> parentConcepts = JwnlAPI.initializeJWNL(selectedHead);
        NewConcept newConcept = new NewConcept(conceptNameTxtFld.getText(), defineNewConceptTxtArea.getText(), selectedHead);
        
        for (ParentConcept parentConcept : parentConcepts) {
            System.out.println("==============================");
            System.out.println("lemma : "+parentConcept.lemma);
            System.out.println("gloss : "+parentConcept.gloss);
            System.out.println("POS : "+parentConcept.pos);
            System.out.println("==============================");
        }
        
        SelectParentConcept selectParentConcept = new SelectParentConcept(newConcept, parentConcepts);
        selectParentConcept.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_nextButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        Home home = new Home();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DefineNewConcept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DefineNewConcept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DefineNewConcept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DefineNewConcept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new DefineNewConcept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox conceptHeadComboBox;
    private java.awt.Label conceptNameLbl;
    private java.awt.TextField conceptNameTxtFld;
    private java.awt.Label defineNewConceptLbl;
    private javax.swing.JTextArea defineNewConceptTxtArea;
    private java.awt.Label headNewConceptLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextButton;
    private java.awt.Label titlelabel;
    // End of variables declaration//GEN-END:variables
}
