/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enrichingexistingontology;

import com.eeo.model.NewConcept;
import com.eeo.model.ParentConcept;

/**
 *
 * @author jabed hasan
 */
public class MappingNewConcept extends javax.swing.JFrame {

    /**
     * Creates new form MappingNewConcept
     */
    NewConcept newConcept;
    ParentConcept parentConcept;
    
    public MappingNewConcept(NewConcept newConcept,ParentConcept parentConcept) {
        this.newConcept = newConcept;
        this.parentConcept = parentConcept;
        initComponents();
        initUI();
    }

    public void initUI(){
        wiki_head_lbl.setText("Wiki Category Head : "+newConcept.currentWikiCategoryHead);
        selected_head_lbl.setText("Selected Head : "+newConcept.currentWikiCategoryHead);
        alt_dfntion_lbl.setText("Alternative Definition"); 
        defineNewConceptTxtArea.setText(""+newConcept.alternativeDefinition); 
        parent_concept_head_lbl.setText("Parent Concept Head : "+parentConcept.lemma);
        parent_concept_id_lbl.setText("Parent Concept Id : "+parentConcept.id);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        wiki_head_lbl = new javax.swing.JLabel();
        alt_dfntion_lbl = new javax.swing.JLabel();
        parent_concept_head_lbl = new javax.swing.JLabel();
        parent_concept_id_lbl = new javax.swing.JLabel();
        selected_head_lbl = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        defineNewConceptTxtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enriching Existing Ontology");

        titleLbl.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(37, 56, 96));
        titleLbl.setText("Mapping New Concept");

        wiki_head_lbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        wiki_head_lbl.setForeground(new java.awt.Color(37, 56, 96));
        wiki_head_lbl.setText("Current wiki-Category Head");

        alt_dfntion_lbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        alt_dfntion_lbl.setForeground(new java.awt.Color(37, 56, 96));
        alt_dfntion_lbl.setText("Alternative Definition");

        parent_concept_head_lbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        parent_concept_head_lbl.setForeground(new java.awt.Color(37, 56, 96));
        parent_concept_head_lbl.setText("Parent Concept Head");

        parent_concept_id_lbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        parent_concept_id_lbl.setForeground(new java.awt.Color(37, 56, 96));
        parent_concept_id_lbl.setText("Parent Concept Id");

        selected_head_lbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        selected_head_lbl.setForeground(new java.awt.Color(37, 56, 96));
        selected_head_lbl.setText("Selected Head");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Confirm Mapping");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        defineNewConceptTxtArea.setColumns(20);
        defineNewConceptTxtArea.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        defineNewConceptTxtArea.setRows(5);
        jScrollPane1.setViewportView(defineNewConceptTxtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(parent_concept_head_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(parent_concept_id_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wiki_head_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selected_head_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(746, 746, 746))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(alt_dfntion_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1333, 1333, 1333))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelButton)
                                .addGap(223, 223, 223)
                                .addComponent(nextButton)))))
                .addGap(566, 566, 566))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(wiki_head_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(selected_head_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(alt_dfntion_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parent_concept_head_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(parent_concept_id_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(nextButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
       System.out.println("Here need to map new concept");
    }//GEN-LAST:event_nextButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        Home home = new Home();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MappingNewConcept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MappingNewConcept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MappingNewConcept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MappingNewConcept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new MappingNewConcept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alt_dfntion_lbl;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextArea defineNewConceptTxtArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel parent_concept_head_lbl;
    private javax.swing.JLabel parent_concept_id_lbl;
    private javax.swing.JLabel selected_head_lbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel wiki_head_lbl;
    // End of variables declaration//GEN-END:variables
}
