/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enrichingexistingontology;

import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumnModel;
import com.eeo.OpenNLP.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Jabed hasan
 */
public class NewConceptList extends javax.swing.JFrame {

    /**
     * Creates new form SuggestionSelection
     */
    DefaultTableModel model;
    String sentences[];
    String selectedValue = "";
    String titleConcept = "";
    public NewConceptList(String sentences[],String titleConcept) {
        initComponents();
        this.sentences = sentences;
        this.titleConcept = titleConcept;
        model = (DefaultTableModel) suggestedCncptTable.getModel();
        initUI();
    }
    
    public void initUI(){
        titlelabel.setText(titleConcept+" Suggested Concept ");
         for (int i=0; i< 5 ;i++) {
            //model.insertRow(model.getColumnCount(), new Object[]{ sentences[i] });
            model.addRow(new Object[]{ sentences[i] });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        suggestedCncptTable = new javax.swing.JTable();
        nextButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        titlelabel = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enriching Existing Ontology");

        suggestedCncptTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        suggestedCncptTable.setFont(new java.awt.Font("Malayalam MN", 1, 14)); // NOI18N
        suggestedCncptTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Suggested Concept"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        suggestedCncptTable.setColumnSelectionAllowed(true);
        suggestedCncptTable.setRowHeight(45);
        suggestedCncptTable.setRowMargin(5);
        suggestedCncptTable.setSize(new java.awt.Dimension(10, 10));
        suggestedCncptTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                suggestedCncptTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(suggestedCncptTable);
        suggestedCncptTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        titlelabel.setFont(new java.awt.Font("PT Sans Caption", 1, 18)); // NOI18N
        titlelabel.setText("Title");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addGap(201, 201, 201)
                .addComponent(nextButton)
                .addGap(511, 511, 511))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1289, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(titlelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(titlelabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton)
                    .addComponent(cancelButton))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        
        if(selectedValue.equals("")){
          JOptionPane.showMessageDialog(this, "Plz select Value..!");
          return;
        }
        
        try {
            System.out.println(" selectedValue : "+selectedValue);
            
            String postTag = OpenNLP.POSTag(selectedValue);
            String[] nouns = OpenNLP.extractNouns(postTag);
            System.out.println("nouns : "+nouns.length);
            for (String noun : nouns) {
                System.out.println(" => "+noun);
            }
             DefineNewConcept defineNewConcept = new DefineNewConcept(titleConcept, selectedValue, nouns);
             this.setVisible(false);
             defineNewConcept.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(NewConceptList.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
    }//GEN-LAST:event_nextButtonActionPerformed

    private void suggestedCncptTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suggestedCncptTableMouseClicked
        selectedValue = String.valueOf(model.getValueAt(suggestedCncptTable.getSelectedRow(), 0));
    }//GEN-LAST:event_suggestedCncptTableMouseClicked

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        Home home = new Home();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewConceptList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewConceptList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewConceptList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewConceptList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new NewConceptList().setVisible(true);
            }
        });
    }
    
    public void setTable(javax.swing.JTable table){
        //this.jTable1 = table;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextButton;
    private javax.swing.JTable suggestedCncptTable;
    private java.awt.Label titlelabel;
    // End of variables declaration//GEN-END:variables
}
