/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enrichingexistingontology;

import com.eeo.model.NewConcept;
import com.eeo.model.ParentConcept;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jabed hasan
 */
public class SelectParentConcept extends javax.swing.JFrame {

    /**
     * Creates new form SelectParentConcept
     */
    DefaultTableModel model;
    ArrayList<ParentConcept> parentConcepts;
    NewConcept newConcept;
    ParentConcept parentConcept = null; 
    public SelectParentConcept(NewConcept newConcept,ArrayList<ParentConcept> parentConcepts ) {
        this.newConcept = newConcept;
        this.parentConcepts = parentConcepts;
        initComponents();
        model = (DefaultTableModel) parent_concept_list_table.getModel();
        initUI();
    }

    public void initUI(){
        
        wiki_head_lbl.setText("Current wiki-Category Head : "+newConcept.currentWikiCategoryHead);
        alt_dfntion_lbl.setText("Alternative Definition : ");
        defineNewConceptTxtArea.setText(""+newConcept.alternativeDefinition);
        parent_concept_head_lbl.setText("Parent Concept Head : "+newConcept.parentConceptHead);
        System.out.println("parentConcepts Size : "+parentConcepts.size());
        for (ParentConcept parentConcept : parentConcepts) {
             //model.insertRow(model.getColumnCount(), new Object[]{ parentConcept.lemma,parentConcept.gloss,parentConcept.pos,parentConcept.id });
             model.addRow(new Object[]{ parentConcept.lemma,parentConcept.gloss,parentConcept.pos,parentConcept.id });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        wiki_head_lbl = new javax.swing.JLabel();
        alt_dfntion_lbl = new javax.swing.JLabel();
        parent_concept_head_lbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        parent_concept_list_table = new javax.swing.JTable();
        cancelButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        defineNewConceptTxtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enriching Existing Ontology");

        titleLbl.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(37, 56, 96));
        titleLbl.setText("Select Parent Concept From The Existing Entitypedia");

        wiki_head_lbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        wiki_head_lbl.setForeground(new java.awt.Color(37, 56, 96));
        wiki_head_lbl.setText("Current wiki-Category Head");

        alt_dfntion_lbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        alt_dfntion_lbl.setForeground(new java.awt.Color(37, 56, 96));
        alt_dfntion_lbl.setText("Alternative Definition");

        parent_concept_head_lbl.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        parent_concept_head_lbl.setForeground(new java.awt.Color(37, 56, 96));
        parent_concept_head_lbl.setText("Parent Concept Head");

        parent_concept_list_table.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        parent_concept_list_table.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        parent_concept_list_table.setForeground(new java.awt.Color(37, 56, 96));
        parent_concept_list_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lemma", "Description", "Parts of Speech", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        parent_concept_list_table.setColumnSelectionAllowed(true);
        parent_concept_list_table.setRowHeight(45);
        parent_concept_list_table.setRowMargin(4);
        parent_concept_list_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parent_concept_list_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(parent_concept_list_table);
        parent_concept_list_table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        defineNewConceptTxtArea.setColumns(20);
        defineNewConceptTxtArea.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        defineNewConceptTxtArea.setRows(5);
        jScrollPane2.setViewportView(defineNewConceptTxtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cancelButton)
                .addGap(306, 306, 306)
                .addComponent(nextButton)
                .addGap(552, 552, 552))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 998, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(alt_dfntion_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(wiki_head_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 1316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parent_concept_head_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 1282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wiki_head_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(alt_dfntion_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(parent_concept_head_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parent_concept_list_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parent_concept_list_tableMouseClicked
        parentConcept = new ParentConcept(
                String.valueOf(model.getValueAt(parent_concept_list_table.getSelectedRow(), 0)),
                String.valueOf(model.getValueAt(parent_concept_list_table.getSelectedRow(), 1)), 
                String.valueOf(model.getValueAt(parent_concept_list_table.getSelectedRow(), 2)),
                Long.valueOf(String.valueOf(model.getValueAt(parent_concept_list_table.getSelectedRow(), 3)))
        );
    }//GEN-LAST:event_parent_concept_list_tableMouseClicked

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if(parentConcept == null){
          JOptionPane.showMessageDialog(this, "Please Select A Parent Concept ..!");
          return;
        }
         MappingNewConcept mappingNewConcept = new MappingNewConcept(newConcept, parentConcept);
         mappingNewConcept.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_nextButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        Home home = new Home();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectParentConcept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectParentConcept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectParentConcept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectParentConcept.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new SelectParentConcept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alt_dfntion_lbl;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextArea defineNewConceptTxtArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel parent_concept_head_lbl;
    private javax.swing.JTable parent_concept_list_table;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel wiki_head_lbl;
    // End of variables declaration//GEN-END:variables
}
